# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bddef632aa50ec40898448b598f2fcd2120782706013704603123f190cef177f24e8023611fb6d5ac046517dfcb5657846bea1de50308b46f785cb912155e51a

test:
  secret_key_base: a1097b1e179bca5bc05ac24831814a5a3b7de6e1dc96140fc8f3d70586f87f99d96596747795595121228d7aa5a57a63856a7710cde7560ff78a93863745e573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
